//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEncuesta_LP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EncuestaEntities : DbContext
    {
        public EncuestaEntities()
            : base("name=EncuestaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enc_Categorias> Enc_Categorias { get; set; }
        public virtual DbSet<Enc_Opcion> Enc_Opcion { get; set; }
        public virtual DbSet<Enc_Preguntas> Enc_Preguntas { get; set; }
        public virtual DbSet<Enc_Respuestas> Enc_Respuestas { get; set; }
        public virtual DbSet<Enc_Resultados> Enc_Resultados { get; set; }
        public virtual DbSet<Enc_Usuarios> Enc_Usuarios { get; set; }
        public virtual DbSet<Administracion> Administracion { get; set; }
    }
}
