//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEncuesta_LP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enc_Preguntas
    {
        public int PreguntaId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public string Pregunta { get; set; }
        public Nullable<bool> Multiple { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
