//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEncuesta_LP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enc_Opcion
    {
        public int OpcionId { get; set; }
        public Nullable<int> PreguntaId { get; set; }
        public string NombreOpcion { get; set; }
    }
}
